name: Nox Summary
description: 'Create a job summary from Nox JSON report'
inputs:
  report:
    description: 'path to the JSON report'
    required: true
  title:
    description: 'title for the generated summary section'
    required: false
    default: Nox
branding:
  icon: package
  color: purple

runs:
  using: composite
  steps:
    - name: "Validate input"
      id: helper
      run: >
        python "${GITHUB_ACTION_PATH}/nox_report.py" --report "${REPORT}" --title "${TITLE}" >>${GITHUB_STEP_SUMMARY}
      env:
        REPORT: '${{ inputs.report }}'
        TITLE: '${{ inputs.title }}'
      shell: bash
